/* Recipe library.
 *
 * RECIPE_SOURCES — your favourite recipe websites. Recipes pulled from them
 * go into RECIPES with `source` set to the site's id and `url` pointing to the
 * original page (always credit and link back to the original).
 *
 * Recipe shape:
 * {
 *   id: "unique-slug",
 *   title: "…",
 *   source: "starter" | "<RECIPE_SOURCES id>",
 *   url: "https://…" | null,
 *   meal: "breakfast" | "meal" | "snack" | "drink",
 *   tags: [...keys of TAG_LABELS],
 *   time: minutes,
 *   serves: n,
 *   prepNote: "how to batch / store",
 *   ingredients: ["…"],
 *   steps: ["…"],
 *   thyroidNote: "optional thyroid-specific tip",
 * }
 */

const RECIPE_SOURCES = [
  { id: "starter", name: "Health Coach starters", url: null },
  { id: "vedicdiet", name: "Vedic Diet", url: null }, // TODO: confirm exact site URL
  { id: "vismai", name: "Vismai Food", url: "https://vismaifood.com" },
  { id: "hebbars", name: "Hebbar's Kitchen", url: "https://hebbarskitchen.com" },
  { id: "cleandelicious", name: "Clean & Delicious", url: "https://cleananddelicious.com" },
  { id: "ranveerbrar", name: "Ranveer Brar", url: "https://ranveerbrar.com" },
  { id: "rajshri", name: "Rajshri Food", url: "https://www.youtube.com/@rajshrifood" },
];

const RECIPES = [
  {
    id: "turmeric-egg-bhurji",
    title: "Turmeric veggie egg bhurji",
    source: "starter",
    url: null,
    meal: "breakfast",
    tags: ["protein", "ai", "egg", "quick", "thyroid"],
    time: 12,
    serves: 1,
    prepNote: "Chop onion, tomato and peppers the night before.",
    ingredients: [
      "2 eggs",
      "1 cup chopped spinach",
      "½ onion, ½ tomato, ¼ bell pepper, chopped",
      "¼ tsp turmeric + pinch of black pepper",
      "½ tsp cumin seeds, 1 green chilli (optional)",
      "1 tsp olive oil or ghee",
    ],
    steps: [
      "Heat oil, add cumin, then onion; cook 2 min.",
      "Add tomato, pepper, turmeric and black pepper; cook 2 min.",
      "Add spinach until wilted, then the beaten eggs. Scramble until just set.",
      "Serve with 1 millet roti or on its own with cucumber.",
    ],
  },
  {
    id: "chia-berry-overnight-oats",
    title: "Chia-berry overnight oats (3 jars)",
    source: "starter",
    url: null,
    meal: "breakfast",
    tags: ["fiber", "ai", "prep", "ready"],
    time: 10,
    serves: 3,
    prepNote: "Keeps 3 days in the fridge. Add berries the morning you eat it.",
    ingredients: [
      "1½ cups rolled oats",
      "3 tbsp chia seeds",
      "3 tbsp ground flaxseed",
      "1½ cups Greek yogurt + 1½ cups milk (or unsweetened almond milk)",
      "1 tsp cinnamon",
      "Berries to top",
    ],
    steps: [
      "Divide oats, chia, flax and cinnamon between 3 jars.",
      "Add yogurt and milk, stir well, cover, refrigerate overnight.",
      "Top with berries and a few walnuts to serve.",
    ],
    thyroidNote: "Yogurt contains calcium — eat this at least 4 h after the thyroid pill, or swap yogurt for more almond milk.",
  },
  {
    id: "sunday-egg-muffins",
    title: "Sunday egg muffins (12)",
    source: "starter",
    url: null,
    meal: "breakfast",
    tags: ["protein", "egg", "prep", "thyroid"],
    time: 30,
    serves: 6,
    prepNote: "Fridge 4 days or freeze; reheat 45 s.",
    ingredients: [
      "8 eggs",
      "1 cup chopped spinach",
      "1 bell pepper, ½ onion, 6 mushrooms, chopped",
      "50 g crumbled paneer or feta",
      "½ tsp turmeric, black pepper, salt",
    ],
    steps: [
      "Heat oven to 180 °C / 350 °F; grease a 12-cup muffin tin.",
      "Divide vegetables and paneer between cups.",
      "Whisk eggs with spices; pour over vegetables.",
      "Bake 20–22 min until set. Cool before storing.",
    ],
  },
  {
    id: "masoor-dal-soup",
    title: "Anti-inflammatory masoor dal soup",
    source: "starter",
    url: null,
    meal: "meal",
    tags: ["protein", "fiber", "ai", "prep", "lowcal"],
    time: 30,
    serves: 4,
    prepNote: "Portion into jars; fridge 4 days, freezer 2 months.",
    ingredients: [
      "1 cup red lentils (masoor), rinsed",
      "1 carrot, 1 tomato, 1 onion, chopped",
      "1 inch ginger + 3 garlic cloves, grated",
      "1 tsp turmeric, 1 tsp cumin, black pepper",
      "2 cups spinach",
      "1 tbsp olive oil, lemon to finish",
    ],
    steps: [
      "Sauté onion, ginger and garlic in oil for 3 min.",
      "Add spices, carrot, tomato; cook 2 min.",
      "Add lentils and 4 cups water; simmer 20 min until soft.",
      "Stir in spinach; blend partly if you like. Finish with lemon.",
    ],
  },
  {
    id: "quinoa-chickpea-salad",
    title: "Quinoa chickpea meal-prep salad",
    source: "starter",
    url: null,
    meal: "meal",
    tags: ["protein", "fiber", "ai", "prep", "ready"],
    time: 25,
    serves: 4,
    prepNote: "Keep dressing separate; lasts 4 days.",
    ingredients: [
      "1 cup quinoa, cooked and cooled",
      "1 can chickpeas, rinsed",
      "1 cucumber, 1 bell pepper, 1 cup cherry tomatoes, ¼ red onion",
      "Handful parsley or coriander",
      "Dressing: 3 tbsp olive oil, 1 lemon, 1 tsp cumin, salt, pepper",
      "Optional: 2 tbsp pumpkin seeds per serving",
    ],
    steps: [
      "Chop vegetables; combine with quinoa and chickpeas.",
      "Shake the dressing in a jar.",
      "Divide into 4 boxes. Add dressing and seeds just before eating.",
    ],
  },
  {
    id: "golden-milk",
    title: "Evening golden milk",
    source: "starter",
    url: null,
    meal: "drink",
    tags: ["ai"],
    time: 5,
    serves: 1,
    prepNote: "",
    ingredients: [
      "1 cup unsweetened milk (dairy or almond)",
      "½ tsp turmeric, pinch black pepper",
      "¼ tsp cinnamon, ½ inch grated ginger",
    ],
    steps: ["Warm everything together for 3–4 min; strain if you like. No sugar needed."],
    thyroidNote: "Drink in the evening, well away from the morning thyroid pill.",
  },
  {
    id: "spiced-makhana",
    title: "Turmeric-pepper roasted makhana",
    source: "starter",
    url: null,
    meal: "snack",
    tags: ["lowcal", "prep", "ready"],
    time: 10,
    serves: 4,
    prepNote: "Airtight jar, 1 week.",
    ingredients: ["4 cups makhana", "1 tsp ghee or olive oil", "¼ tsp turmeric, ½ tsp black pepper, salt, chaat masala"],
    steps: ["Dry-roast makhana on low heat 6–8 min until crisp.", "Add oil and spices, toss 1 more minute. Cool fully before storing."],
  },
];
